/* Auto-generated from Desktop/عملاء — client work data */
const CLIENTS = [
  {
    slug: "menu-gps",
    client: 'منيو GPS',
    titleEn: 'GPS — Digital Menu & App UI',
    images: ["assets/images/clients/menu-gps/img-01.jpg", "assets/images/clients/menu-gps/img-02.jpg", "assets/images/clients/menu-gps/img-03.jpg", "assets/images/clients/menu-gps/img-04.jpg", "assets/images/clients/menu-gps/img-05.jpg", "assets/images/clients/menu-gps/img-06.jpg", "assets/images/clients/menu-gps/img-07.jpg", "assets/images/clients/menu-gps/img-08.jpg"],
    videos: [],
  },
  {
    slug: "cafe-gps",
    client: 'كافيه GPS',
    titleEn: 'Cafe GPS — Padel & Gaming',
    images: ["assets/images/clients/cafe-gps/01-padel.jpg", "assets/images/clients/cafe-gps/02-play-padel.jpg", "assets/images/clients/cafe-gps/03-eid-playstation.jpg", "assets/images/clients/cafe-gps/04-game-zone.jpg", "assets/images/clients/cafe-gps/img-05.jpg", "assets/images/clients/cafe-gps/img-06.jpg", "assets/images/clients/cafe-gps/img-07.jpg", "assets/images/clients/cafe-gps/img-08.jpg", "assets/images/clients/cafe-gps/img-09.jpg", "assets/images/clients/cafe-gps/img-10.jpg", "assets/images/clients/cafe-gps/img-11.jpg", "assets/images/clients/cafe-gps/img-12.jpg", "assets/images/clients/cafe-gps/img-13.jpg", "assets/images/clients/cafe-gps/img-14.jpg", "assets/images/clients/cafe-gps/img-15.jpg", "assets/images/clients/cafe-gps/img-16.jpg", "assets/images/clients/cafe-gps/img-17.jpg", "assets/images/clients/cafe-gps/img-18.jpg", "assets/images/clients/cafe-gps/img-19.jpg", "assets/images/clients/cafe-gps/img-20.jpg", "assets/images/clients/cafe-gps/img-21.jpg", "assets/images/clients/cafe-gps/img-22.jpg", "assets/images/clients/cafe-gps/img-23.jpg", "assets/images/clients/cafe-gps/img-24.jpg", "assets/images/clients/cafe-gps/img-25.jpg", "assets/images/clients/cafe-gps/img-26.jpg", "assets/images/clients/cafe-gps/img-27.jpg", "assets/images/clients/cafe-gps/img-28.jpg", "assets/images/clients/cafe-gps/img-29.jpg", "assets/images/clients/cafe-gps/img-30.jpg", "assets/images/clients/cafe-gps/img-31.jpg", "assets/images/clients/cafe-gps/img-32.jpg", "assets/images/clients/cafe-gps/img-33.jpg", "assets/images/clients/cafe-gps/img-34.jpg", "assets/images/clients/cafe-gps/img-35.jpg", "assets/images/clients/cafe-gps/img-36.jpg", "assets/images/clients/cafe-gps/img-37.jpg", "assets/images/clients/cafe-gps/img-38.jpg", "assets/images/clients/cafe-gps/img-39.jpg", "assets/images/clients/cafe-gps/img-40.jpg", "assets/images/clients/cafe-gps/img-41.jpg", "assets/images/clients/cafe-gps/img-42.jpg", "assets/images/clients/cafe-gps/img-43.jpg", "assets/images/clients/cafe-gps/img-44.jpg", "assets/images/clients/cafe-gps/img-45.jpg", "assets/images/clients/cafe-gps/img-46.jpg", "assets/images/clients/cafe-gps/img-47.jpg", "assets/images/clients/cafe-gps/img-48.jpg", "assets/images/clients/cafe-gps/img-49.jpg", "assets/images/clients/cafe-gps/img-50.jpg", "assets/images/clients/cafe-gps/img-51.jpg", "assets/images/clients/cafe-gps/img-52.jpg", "assets/images/clients/cafe-gps/img-53.jpg", "assets/images/clients/cafe-gps/img-54.jpg", "assets/images/clients/cafe-gps/img-55.jpg", "assets/images/clients/cafe-gps/img-56.jpg", "assets/images/clients/cafe-gps/img-57.jpg", "assets/images/clients/cafe-gps/img-58.jpg", "assets/images/clients/cafe-gps/img-59.jpg", "assets/images/clients/cafe-gps/img-60.jpg", "assets/images/clients/cafe-gps/img-61.jpg", "assets/images/clients/cafe-gps/img-62.jpg", "assets/images/clients/cafe-gps/img-63.jpg", "assets/images/clients/cafe-gps/img-64.jpg", "assets/images/clients/cafe-gps/img-65.jpg", "assets/images/clients/cafe-gps/img-66.jpg", "assets/images/clients/cafe-gps/img-67.jpg", "assets/images/clients/cafe-gps/img-68.jpg", "assets/images/clients/cafe-gps/img-69.jpg", "assets/images/clients/cafe-gps/img-70.jpg", "assets/images/clients/cafe-gps/img-71.jpg", "assets/images/clients/cafe-gps/img-72.jpg", "assets/images/clients/cafe-gps/img-73.jpg", "assets/images/clients/cafe-gps/img-74.jpg", "assets/images/clients/cafe-gps/img-75.jpg", "assets/images/clients/cafe-gps/img-76.jpg", "assets/images/clients/cafe-gps/img-77.jpg", "assets/images/clients/cafe-gps/img-78.jpg", "assets/images/clients/cafe-gps/img-79.jpg", "assets/images/clients/cafe-gps/img-80.jpg", "assets/images/clients/cafe-gps/img-81.jpg", "assets/images/clients/cafe-gps/img-82.jpg", "assets/images/clients/cafe-gps/img-83.jpg", "assets/images/clients/cafe-gps/img-84.jpg", "assets/images/clients/cafe-gps/img-85.jpg", "assets/images/clients/cafe-gps/img-86.jpg", "assets/images/clients/cafe-gps/img-87.jpg"],
    videos: ["assets/videos/clientvid-e79601f6.mp4"],
  },
  {
    slug: "vinoks",
    client: 'فينوكس',
    titleEn: 'Vinoks — Product Catalog',
    images: ["assets/images/clients/vinoks/01-cover.jpg", "assets/images/clients/vinoks/02-page.jpg", "assets/images/clients/vinoks/03-page.jpg", "assets/images/clients/vinoks/04-page.jpg", "assets/images/clients/vinoks/img-05.jpg", "assets/images/clients/vinoks/img-06.jpg", "assets/images/clients/vinoks/img-07.jpg", "assets/images/clients/vinoks/img-08.jpg", "assets/images/clients/vinoks/img-09.jpg", "assets/images/clients/vinoks/img-10.jpg", "assets/images/clients/vinoks/img-11.jpg", "assets/images/clients/vinoks/img-12.jpg", "assets/images/clients/vinoks/img-13.jpg", "assets/images/clients/vinoks/img-14.jpg", "assets/images/clients/vinoks/img-15.jpg", "assets/images/clients/vinoks/img-16.jpg", "assets/images/clients/vinoks/img-17.jpg", "assets/images/clients/vinoks/img-18.jpg", "assets/images/clients/vinoks/img-19.jpg", "assets/images/clients/vinoks/img-20.jpg", "assets/images/clients/vinoks/img-21.jpg", "assets/images/clients/vinoks/img-22.jpg", "assets/images/clients/vinoks/img-23.jpg", "assets/images/clients/vinoks/img-24.jpg", "assets/images/clients/vinoks/img-25.jpg", "assets/images/clients/vinoks/img-26.jpg", "assets/images/clients/vinoks/img-27.jpg", "assets/images/clients/vinoks/img-28.jpg", "assets/images/clients/vinoks/img-29.jpg", "assets/images/clients/vinoks/img-30.jpg", "assets/images/clients/vinoks/img-31.jpg", "assets/images/clients/vinoks/img-32.jpg", "assets/images/clients/vinoks/img-33.jpg", "assets/images/clients/vinoks/img-34.jpg", "assets/images/clients/vinoks/img-35.jpg", "assets/images/clients/vinoks/img-36.jpg", "assets/images/clients/vinoks/img-37.jpg", "assets/images/clients/vinoks/img-38.jpg", "assets/images/clients/vinoks/img-39.jpg", "assets/images/clients/vinoks/img-40.jpg", "assets/images/clients/vinoks/img-41.jpg"],
    videos: [],
  },
  {
    slug: "techno-engineer",
    client: 'تكنو انجنير',
    titleEn: 'Techno Engineer — Company Profile',
    images: ["assets/images/clients/techno-engineer/01-cover.jpg", "assets/images/clients/techno-engineer/02-identity.jpg", "assets/images/clients/techno-engineer/03-contact.jpg", "assets/images/clients/techno-engineer/04-logo.jpg", "assets/images/clients/techno-engineer/img-05.jpg", "assets/images/clients/techno-engineer/img-06.jpg", "assets/images/clients/techno-engineer/img-07.jpg", "assets/images/clients/techno-engineer/img-08.jpg", "assets/images/clients/techno-engineer/img-09.jpg", "assets/images/clients/techno-engineer/img-10.jpg", "assets/images/clients/techno-engineer/img-11.jpg", "assets/images/clients/techno-engineer/img-12.jpg", "assets/images/clients/techno-engineer/img-13.jpg", "assets/images/clients/techno-engineer/img-14.jpg", "assets/images/clients/techno-engineer/img-15.jpg", "assets/images/clients/techno-engineer/img-16.jpg", "assets/images/clients/techno-engineer/img-17.jpg", "assets/images/clients/techno-engineer/img-18.jpg", "assets/images/clients/techno-engineer/img-19.jpg", "assets/images/clients/techno-engineer/img-20.jpg", "assets/images/clients/techno-engineer/img-21.jpg", "assets/images/clients/techno-engineer/img-22.jpg", "assets/images/clients/techno-engineer/img-23.jpg", "assets/images/clients/techno-engineer/img-24.jpg", "assets/images/clients/techno-engineer/img-25.jpg", "assets/images/clients/techno-engineer/img-26.jpg", "assets/images/clients/techno-engineer/img-27.jpg", "assets/images/clients/techno-engineer/img-28.jpg"],
    videos: [],
  },
  {
    slug: "engaz",
    client: 'شركة انجاز',
    titleEn: 'Engaz — Full Brand Identity',
    images: ["assets/images/clients/engaz/01-cards.jpg", "assets/images/clients/engaz/02-folder.jpg", "assets/images/clients/engaz/03-stationery.jpg", "assets/images/clients/engaz/04-flags.jpg", "assets/images/clients/engaz/img-05.jpg", "assets/images/clients/engaz/img-06.jpg", "assets/images/clients/engaz/img-07.jpg", "assets/images/clients/engaz/img-08.jpg", "assets/images/clients/engaz/img-09.jpg", "assets/images/clients/engaz/img-10.jpg", "assets/images/clients/engaz/img-11.jpg", "assets/images/clients/engaz/img-12.jpg", "assets/images/clients/engaz/img-13.jpg", "assets/images/clients/engaz/img-14.jpg", "assets/images/clients/engaz/img-15.jpg", "assets/images/clients/engaz/img-16.jpg", "assets/images/clients/engaz/img-17.jpg", "assets/images/clients/engaz/img-18.jpg"],
    videos: [],
  },
  {
    slug: "cars-sadat",
    client: 'عربيات - السادات',
    titleEn: 'Cars — Sadat City',
    images: ["assets/images/clients/cars-sadat/img-01.jpg", "assets/images/clients/cars-sadat/img-02.jpg", "assets/images/clients/cars-sadat/img-03.jpg", "assets/images/clients/cars-sadat/img-04.jpg", "assets/images/clients/cars-sadat/img-05.jpg", "assets/images/clients/cars-sadat/img-06.jpg"],
    videos: [],
  },
  {
    slug: "real-estate",
    client: 'عقارات - دولي',
    titleEn: 'Real Estate — International',
    images: ["assets/images/clients/real-estate/img-01.jpg", "assets/images/clients/real-estate/img-02.jpg", "assets/images/clients/real-estate/img-03.jpg", "assets/images/clients/real-estate/img-04.jpg", "assets/images/clients/real-estate/img-05.jpg", "assets/images/clients/real-estate/img-06.jpg", "assets/images/clients/real-estate/img-07.jpg", "assets/images/clients/real-estate/img-08.jpg", "assets/images/clients/real-estate/img-09.jpg"],
    videos: [],
  },
  {
    slug: "clinics",
    client: 'عيادات',
    titleEn: 'Clinics Campaigns',
    images: ["assets/images/clients/clinics/img-01.jpg", "assets/images/clients/clinics/img-02.jpg", "assets/images/clients/clinics/img-03.jpg", "assets/images/clients/clinics/img-04.jpg", "assets/images/clients/clinics/img-05.jpg", "assets/images/clients/clinics/img-06.jpg", "assets/images/clients/clinics/img-07.jpg", "assets/images/clients/clinics/img-08.jpg"],
    videos: [],
  },
  {
    slug: "kahila",
    client: 'كحيلة خليجي',
    titleEn: 'Kahila — Khaleeji Restaurant',
    images: ["assets/images/clients/kahila/01-menu-food.jpg", "assets/images/clients/kahila/02-menu-drinks.jpg", "assets/images/clients/kahila/03-menu-drinks-b.jpg", "assets/images/clients/kahila/doc-05.jpg", "assets/images/clients/kahila/doc-06.jpg", "assets/images/clients/kahila/doc-07.jpg", "assets/images/clients/kahila/img-04.jpg"],
    videos: [],
  },
  {
    slug: "business-cards",
    client: 'كروت شخصية',
    titleEn: 'Business Cards — Private Clients',
    images: ["assets/images/clients/business-cards/img-01.jpg", "assets/images/clients/business-cards/img-02.jpg", "assets/images/clients/business-cards/img-03.jpg", "assets/images/clients/business-cards/img-04.jpg", "assets/images/clients/business-cards/img-05.jpg", "assets/images/clients/business-cards/img-06.jpg", "assets/images/clients/business-cards/img-07.jpg"],
    videos: [],
  },
  {
    slug: "lamsat",
    client: 'لمسات اردنية',
    titleEn: 'Lamsat Ordonia — Makeup',
    images: ["assets/images/clients/lamsat/img-01.jpg", "assets/images/clients/lamsat/img-02.jpg", "assets/images/clients/lamsat/img-03.jpg", "assets/images/clients/lamsat/img-04.jpg"],
    videos: ["assets/videos/clientvid-1e01bb8e.mp4", "assets/videos/clientvid-2b79611f.mp4", "assets/videos/clientvid-3d4eec38.mp4", "assets/videos/clientvid-50ed2ed7.mp4", "assets/videos/clientvid-eed92c87.mp4"],
  },
  {
    slug: "logos",
    client: 'لوجو شركات',
    titleEn: 'Company Logos',
    images: ["assets/images/clients/logos/img-01.jpg", "assets/images/clients/logos/img-02.jpg", "assets/images/clients/logos/img-03.jpg", "assets/images/clients/logos/img-04.jpg"],
    videos: [],
  },
  {
    slug: "facebook-office",
    client: 'مكتب فيسبوك - السادات',
    titleEn: 'Facebook Office — Sadat City',
    images: ["assets/images/clients/facebook-office/01-real-estate.jpg", "assets/images/clients/facebook-office/02-12-design.jpg", "assets/images/clients/facebook-office/03-military.jpg", "assets/images/clients/facebook-office/04-stats.jpg", "assets/images/clients/facebook-office/doc-69.jpg", "assets/images/clients/facebook-office/img-05.jpg", "assets/images/clients/facebook-office/img-06.jpg", "assets/images/clients/facebook-office/img-07.jpg", "assets/images/clients/facebook-office/img-08.jpg", "assets/images/clients/facebook-office/img-09.jpg", "assets/images/clients/facebook-office/img-10.jpg", "assets/images/clients/facebook-office/img-11.jpg", "assets/images/clients/facebook-office/img-12.jpg", "assets/images/clients/facebook-office/img-13.jpg", "assets/images/clients/facebook-office/img-14.jpg", "assets/images/clients/facebook-office/img-15.jpg", "assets/images/clients/facebook-office/img-16.jpg", "assets/images/clients/facebook-office/img-17.jpg", "assets/images/clients/facebook-office/img-18.jpg", "assets/images/clients/facebook-office/img-19.jpg", "assets/images/clients/facebook-office/img-20.jpg", "assets/images/clients/facebook-office/img-21.jpg", "assets/images/clients/facebook-office/img-22.jpg", "assets/images/clients/facebook-office/img-23.jpg", "assets/images/clients/facebook-office/img-24.jpg", "assets/images/clients/facebook-office/img-25.jpg", "assets/images/clients/facebook-office/img-26.jpg", "assets/images/clients/facebook-office/img-27.jpg", "assets/images/clients/facebook-office/img-28.jpg", "assets/images/clients/facebook-office/img-29.jpg", "assets/images/clients/facebook-office/img-30.jpg", "assets/images/clients/facebook-office/img-31.jpg", "assets/images/clients/facebook-office/img-32.jpg", "assets/images/clients/facebook-office/img-33.jpg", "assets/images/clients/facebook-office/img-34.jpg", "assets/images/clients/facebook-office/img-35.jpg", "assets/images/clients/facebook-office/img-36.jpg", "assets/images/clients/facebook-office/img-37.jpg", "assets/images/clients/facebook-office/img-38.jpg", "assets/images/clients/facebook-office/img-39.jpg", "assets/images/clients/facebook-office/img-40.jpg", "assets/images/clients/facebook-office/img-41.jpg", "assets/images/clients/facebook-office/img-42.jpg", "assets/images/clients/facebook-office/img-43.jpg", "assets/images/clients/facebook-office/img-44.jpg", "assets/images/clients/facebook-office/img-45.jpg", "assets/images/clients/facebook-office/img-46.jpg", "assets/images/clients/facebook-office/img-47.jpg", "assets/images/clients/facebook-office/img-48.jpg", "assets/images/clients/facebook-office/img-49.jpg", "assets/images/clients/facebook-office/img-50.jpg", "assets/images/clients/facebook-office/img-51.jpg", "assets/images/clients/facebook-office/img-52.jpg", "assets/images/clients/facebook-office/img-53.jpg", "assets/images/clients/facebook-office/img-54.jpg", "assets/images/clients/facebook-office/img-55.jpg", "assets/images/clients/facebook-office/img-56.jpg", "assets/images/clients/facebook-office/img-57.jpg", "assets/images/clients/facebook-office/img-58.jpg", "assets/images/clients/facebook-office/img-59.jpg", "assets/images/clients/facebook-office/img-60.jpg", "assets/images/clients/facebook-office/img-61.jpg", "assets/images/clients/facebook-office/img-62.jpg", "assets/images/clients/facebook-office/img-63.jpg", "assets/images/clients/facebook-office/img-64.jpg", "assets/images/clients/facebook-office/img-65.jpg", "assets/images/clients/facebook-office/img-66.jpg", "assets/images/clients/facebook-office/img-67.jpg", "assets/images/clients/facebook-office/img-68.jpg", "assets/images/clients/facebook-office/img-70.jpg", "assets/images/clients/facebook-office/img-71.jpg", "assets/images/clients/facebook-office/img-72.jpg", "assets/images/clients/facebook-office/img-73.jpg", "assets/images/clients/facebook-office/img-74.jpg", "assets/images/clients/facebook-office/img-75.jpg", "assets/images/clients/facebook-office/img-76.jpg", "assets/images/clients/facebook-office/img-77.jpg", "assets/images/clients/facebook-office/img-78.jpg", "assets/images/clients/facebook-office/img-79.jpg", "assets/images/clients/facebook-office/img-80.jpg", "assets/images/clients/facebook-office/img-81.jpg", "assets/images/clients/facebook-office/img-82.jpg"],
    videos: [],
  },
  {
    slug: "aruf",
    client: 'منيو عروف',
    titleEn: 'Aruf Restaurant Menu',
    images: ["assets/images/clients/aruf/01-menu.jpg", "assets/images/clients/aruf/02-menu.jpg", "assets/images/clients/aruf/03-menu.jpg", "assets/images/clients/aruf/04-menu.jpg", "assets/images/clients/aruf/img-05.jpg", "assets/images/clients/aruf/img-06.jpg", "assets/images/clients/aruf/img-07.jpg", "assets/images/clients/aruf/img-08.jpg", "assets/images/clients/aruf/img-09.jpg", "assets/images/clients/aruf/img-10.jpg", "assets/images/clients/aruf/img-11.jpg", "assets/images/clients/aruf/img-12.jpg", "assets/images/clients/aruf/img-13.jpg", "assets/images/clients/aruf/img-14.jpg"],
    videos: [],
  },
  {
    slug: "ghin",
    client: 'منيو غين',
    titleEn: 'Ghin Restaurant Menu',
    images: ["assets/images/clients/ghin/01-menu-a.jpg", "assets/images/clients/ghin/02-menu-b.jpg", "assets/images/clients/ghin/doc-03.jpg", "assets/images/clients/ghin/doc-04.jpg"],
    videos: [],
  },
  {
    slug: "level-one",
    client: 'موبيلات Level One',
    titleEn: 'Level One — Mobiles',
    images: ["assets/images/clients/level-one/img-01.jpg", "assets/images/clients/level-one/img-02.jpg", "assets/images/clients/level-one/img-03.jpg", "assets/images/clients/level-one/img-04.jpg", "assets/images/clients/level-one/img-05.jpg", "assets/images/clients/level-one/img-06.jpg", "assets/images/clients/level-one/img-07.jpg", "assets/images/clients/level-one/img-08.jpg", "assets/images/clients/level-one/img-09.jpg", "assets/images/clients/level-one/img-10.jpg", "assets/images/clients/level-one/img-11.jpg"],
    videos: [],
  },
  {
    slug: "bb-makeup",
    client: 'ميكب B&B',
    titleEn: 'B&B — Makeup Studio',
    images: ["assets/images/clients/bb-makeup/01-logo.jpg", "assets/images/clients/bb-makeup/02-post.jpg", "assets/images/clients/bb-makeup/03-post.jpg", "assets/images/clients/bb-makeup/doc-89.jpg", "assets/images/clients/bb-makeup/doc-90.jpg", "assets/images/clients/bb-makeup/img-04.jpg", "assets/images/clients/bb-makeup/img-05.jpg", "assets/images/clients/bb-makeup/img-06.jpg", "assets/images/clients/bb-makeup/img-07.jpg", "assets/images/clients/bb-makeup/img-08.jpg", "assets/images/clients/bb-makeup/img-09.jpg", "assets/images/clients/bb-makeup/img-10.jpg", "assets/images/clients/bb-makeup/img-11.jpg", "assets/images/clients/bb-makeup/img-12.jpg", "assets/images/clients/bb-makeup/img-13.jpg", "assets/images/clients/bb-makeup/img-14.jpg", "assets/images/clients/bb-makeup/img-15.jpg", "assets/images/clients/bb-makeup/img-16.jpg", "assets/images/clients/bb-makeup/img-17.jpg", "assets/images/clients/bb-makeup/img-18.jpg", "assets/images/clients/bb-makeup/img-19.jpg", "assets/images/clients/bb-makeup/img-20.jpg", "assets/images/clients/bb-makeup/img-21.jpg", "assets/images/clients/bb-makeup/img-22.jpg", "assets/images/clients/bb-makeup/img-23.jpg", "assets/images/clients/bb-makeup/img-24.jpg", "assets/images/clients/bb-makeup/img-25.jpg", "assets/images/clients/bb-makeup/img-26.jpg", "assets/images/clients/bb-makeup/img-27.jpg", "assets/images/clients/bb-makeup/img-28.jpg", "assets/images/clients/bb-makeup/img-29.jpg", "assets/images/clients/bb-makeup/img-30.jpg", "assets/images/clients/bb-makeup/img-31.jpg", "assets/images/clients/bb-makeup/img-32.jpg", "assets/images/clients/bb-makeup/img-33.jpg", "assets/images/clients/bb-makeup/img-34.jpg", "assets/images/clients/bb-makeup/img-35.jpg", "assets/images/clients/bb-makeup/img-36.jpg", "assets/images/clients/bb-makeup/img-37.jpg", "assets/images/clients/bb-makeup/img-38.jpg", "assets/images/clients/bb-makeup/img-39.jpg", "assets/images/clients/bb-makeup/img-40.jpg", "assets/images/clients/bb-makeup/img-41.jpg", "assets/images/clients/bb-makeup/img-42.jpg", "assets/images/clients/bb-makeup/img-43.jpg", "assets/images/clients/bb-makeup/img-44.jpg", "assets/images/clients/bb-makeup/img-45.jpg", "assets/images/clients/bb-makeup/img-46.jpg", "assets/images/clients/bb-makeup/img-47.jpg", "assets/images/clients/bb-makeup/img-48.jpg", "assets/images/clients/bb-makeup/img-49.jpg", "assets/images/clients/bb-makeup/img-50.jpg", "assets/images/clients/bb-makeup/img-51.jpg", "assets/images/clients/bb-makeup/img-52.jpg", "assets/images/clients/bb-makeup/img-53.jpg", "assets/images/clients/bb-makeup/img-54.jpg", "assets/images/clients/bb-makeup/img-55.jpg", "assets/images/clients/bb-makeup/img-56.jpg", "assets/images/clients/bb-makeup/img-57.jpg", "assets/images/clients/bb-makeup/img-58.jpg", "assets/images/clients/bb-makeup/img-59.jpg", "assets/images/clients/bb-makeup/img-60.jpg", "assets/images/clients/bb-makeup/img-61.jpg", "assets/images/clients/bb-makeup/img-62.jpg", "assets/images/clients/bb-makeup/img-63.jpg", "assets/images/clients/bb-makeup/img-64.jpg", "assets/images/clients/bb-makeup/img-65.jpg", "assets/images/clients/bb-makeup/img-66.jpg", "assets/images/clients/bb-makeup/img-67.jpg", "assets/images/clients/bb-makeup/img-68.jpg", "assets/images/clients/bb-makeup/img-69.jpg", "assets/images/clients/bb-makeup/img-70.jpg", "assets/images/clients/bb-makeup/img-71.jpg", "assets/images/clients/bb-makeup/img-72.jpg", "assets/images/clients/bb-makeup/img-73.jpg", "assets/images/clients/bb-makeup/img-74.jpg", "assets/images/clients/bb-makeup/img-75.jpg", "assets/images/clients/bb-makeup/img-76.jpg", "assets/images/clients/bb-makeup/img-77.jpg", "assets/images/clients/bb-makeup/img-78.jpg", "assets/images/clients/bb-makeup/img-79.jpg", "assets/images/clients/bb-makeup/img-80.jpg", "assets/images/clients/bb-makeup/img-81.jpg", "assets/images/clients/bb-makeup/img-82.jpg", "assets/images/clients/bb-makeup/img-83.jpg", "assets/images/clients/bb-makeup/img-84.jpg", "assets/images/clients/bb-makeup/img-85.jpg", "assets/images/clients/bb-makeup/img-86.jpg", "assets/images/clients/bb-makeup/img-87.jpg", "assets/images/clients/bb-makeup/img-88.jpg", "assets/images/clients/bb-makeup/img-91.jpg"],
    videos: [],
  },
  {
    slug: "nightclub",
    client: 'نايت كلوب',
    titleEn: 'Nightclub Events',
    images: ["assets/images/clients/nightclub/01-rotana.jpg", "assets/images/clients/nightclub/02-friday.jpg", "assets/images/clients/nightclub/03-grand-opening.jpg", "assets/images/clients/nightclub/04-saturday.jpg", "assets/images/clients/nightclub/img-05.jpg", "assets/images/clients/nightclub/img-06.jpg", "assets/images/clients/nightclub/img-07.jpg", "assets/images/clients/nightclub/img-08.jpg", "assets/images/clients/nightclub/img-09.jpg", "assets/images/clients/nightclub/img-10.jpg", "assets/images/clients/nightclub/img-11.jpg", "assets/images/clients/nightclub/img-12.jpg", "assets/images/clients/nightclub/img-13.jpg", "assets/images/clients/nightclub/img-14.jpg", "assets/images/clients/nightclub/img-15.jpg", "assets/images/clients/nightclub/img-16.jpg", "assets/images/clients/nightclub/img-17.jpg", "assets/images/clients/nightclub/img-18.jpg", "assets/images/clients/nightclub/img-19.jpg", "assets/images/clients/nightclub/img-20.jpg", "assets/images/clients/nightclub/img-21.jpg", "assets/images/clients/nightclub/img-22.jpg", "assets/images/clients/nightclub/img-23.jpg", "assets/images/clients/nightclub/img-24.jpg", "assets/images/clients/nightclub/img-25.jpg", "assets/images/clients/nightclub/img-26.jpg", "assets/images/clients/nightclub/img-27.jpg", "assets/images/clients/nightclub/img-28.jpg", "assets/images/clients/nightclub/img-29.jpg", "assets/images/clients/nightclub/img-30.jpg"],
    videos: [],
  },
  {
    slug: "client-cvs",
    client: 'سير ذاتية عملاء',
    titleEn: 'Client CV Designs',
    images: [
      "assets/images/clients/client-cvs/01-cv-reem.jpg",
      "assets/images/clients/client-cvs/02-cv-yazan.jpg",
      "assets/images/clients/client-cvs/03-cv-abanoub.jpg",
      "assets/images/clients/client-cvs/04-cv-gamel.jpg",
      "assets/images/clients/client-cvs/05-cv-abdelrahim.jpg",
      "assets/images/clients/client-cvs/cv-ehdaa-01.jpg",
      "assets/images/clients/client-cvs/cv-walaa-01.jpg",
      "assets/images/clients/client-cvs/cv-ahmed-zaki-01.jpg",
      "assets/images/clients/client-cvs/cv-ahmed-zaki-02.jpg",
      "assets/images/clients/client-cvs/cv-ahmed-zaki-03.jpg",
      "assets/images/clients/client-cvs/cv-ahmed-zaki-04.jpg",
      "assets/images/clients/client-cvs/cv-ahmed-zaki-05.jpg",
      "assets/images/clients/client-cvs/cv-reem-new-01.jpg",
      "assets/images/clients/client-cvs/cv-reem-new-02.jpg"
    ],
    videos: [],
  },
];
